import { generate, solve, leaves, groups, number as f, readCode, checkAnswer } from './circuit.js';
import { randomSeed } from '../../shared/services/exercises.js';
let exercise=null,shown=0,fields=[];
const link=p=>`#lab-005${p?'/'+p:''}`;
export function schematic(ex,collapsed=new Set(),highlight=new Set()){
 const size=n=>collapsed.has(n.id)||n.type==='R'?{w:110,h:90}:n.type==='S'?{w:n.children.reduce((s,c)=>s+size(c).w,0),h:Math.max(...n.children.map(c=>size(c).h))}:{w:Math.max(...n.children.map(c=>size(c).w))+40,h:n.children.reduce((s,c)=>s+size(c).h,0)};
 const line=(x,y,a,b)=>`<line x1="${x}" y1="${y}" x2="${a}" y2="${b}"/>`;
 const draw=(n,x,y)=>{const s=size(n);if(n.type==='R'||collapsed.has(n.id))return `<g class="${highlight.has(n.id)?'focus':''}">${line(x,y,x+30,y)}<rect x="${x+30}" y="${y-9}" width="50" height="18"/>${line(x+80,y,x+110,y)}<text x="${x+55}" y="${y-18}" text-anchor="middle">${n.id}</text><text x="${x+55}" y="${y+30}" text-anchor="middle">${f(n.resistance)} Ω</text></g>`;if(n.type==='S'){let xx=x;return n.children.map(c=>{const svg=draw(c,xx,y);xx+=size(c).w;return svg;}).join('');}let yy=y-s.h/2;const centers=n.children.map(c=>{const cy=yy+size(c).h/2;yy+=size(c).h;return cy;});let out=line(x,y,x+12,y)+line(x+s.w-12,y,x+s.w,y)+line(x+12,centers[0],x+12,centers.at(-1))+line(x+s.w-12,centers[0],x+s.w-12,centers.at(-1));n.children.forEach((c,i)=>{const cx=x+(s.w-size(c).w)/2;out+=line(x+12,centers[i],cx,centers[i])+draw(c,cx,centers[i])+line(cx+size(c).w,centers[i],x+s.w-12,centers[i]);});return out;};
 const s=size(ex.root),x=110,y=s.h/2+30,bottom=s.h+90,right=x+s.w+25,sy=(y+bottom)/2;
 return `<svg class="cc-scheme" viewBox="0 0 ${right+25} ${bottom+25}" role="img" aria-label="Circuit amb font de ${ex.voltage} volts; ${leaves(ex.root).map(r=>r.id+' '+r.value+' ohms').join(', ')}"><title>Circuit resistiu. Les connexions es descriuen a l’enunciat.</title>${draw(ex.root,x,y)}${line(65,y,x,y)}${line(x+s.w,y,right,y)}${line(right,y,right,bottom)}${line(right,bottom,65,bottom)}${line(65,y,65,sy-15)}${line(65,sy+15,65,bottom)}<circle cx="65" cy="${sy}" r="15"/><text x="65" y="${sy-2}" text-anchor="middle">+</text><text x="65" y="${sy+12}" text-anchor="middle">−</text><text x="8" y="${sy+35}">${f(ex.voltage)} V</text><text x="85" y="${y-12}">I →</text></svg>`;
}
const expression=n=>n.type==='R'?n.id:`(${n.children.map(expression).join(n.type==='S'?' + ':' ∥ ')})`;
function steps(ex){const gs=groups(ex.root),out=[],collapsed=new Set();out.push({title:'Identifica les connexions',html:`<p>${expression(ex.root)}. El signe + indica sèrie; ∥ indica paral·lel. En sèrie circula el mateix corrent. En paral·lel les branques tenen la mateixa tensió.</p>`});
 for(const g of gs){const values=g.children.map(c=>f(c.resistance));collapsed.add(g.id);out.push({title:`Redueix ${g.id}: ${g.type==='S'?'sèrie':'paral·lel'}`,html:`<p>${g.children.map(c=>c.id).join(' i ')}: ${g.type==='S'?values.join(' + '):'1 / ('+values.map(v=>'1 / '+v).join(' + ')+')'} = ${f(g.resistance)} Ω.</p>${schematic(ex,new Set(collapsed),new Set([g.id]))}`});}
 out.push({title:'Calcula el corrent total',html:`<p>R equivalent = ${f(ex.root.resistance)} Ω. I = V / R = ${f(ex.voltage)} / ${f(ex.root.resistance)} = ${f(ex.root.current)} A.</p>`});
 const expand=n=>{if(n.type==='R')return;collapsed.delete(n.id);out.push({title:`Reparteix ${n.type==='S'?'les tensions':'els corrents'} a ${n.id}`,html:`<p>${n.type==='S'?'Mateix corrent a tots els elements; V = I · R.':'Mateixa tensió a totes les branques; I = V / R.'}</p>${n.children.map(c=>`<p>${c.id}: V = ${f(c.voltage)} V; I = ${f(c.current)} A.</p>`).join('')}<p>Kirchhoff: ${n.children.map(c=>f(n.type==='S'?c.voltage:c.current)).join(' + ')} = ${f(n.type==='S'?n.voltage:n.current)} ${n.type==='S'?'V':'A'}.</p>${schematic(ex,new Set(collapsed),new Set(n.children.map(c=>c.id)))}`});n.children.forEach(expand);};expand(ex.root);
 out.push({title:'Calcula les potències i comprova el balanç',html:leaves(ex.root).map(r=>`<p>${r.id}: P = V · I = ${f(r.voltage)} · ${f(r.current)} = ${f(r.power)} W.</p>`).join('')+`<p>Font: P = ${f(ex.voltage)} · ${f(ex.root.current)} = ${f(ex.root.power)} W. Suma de potències dissipades = ${f(leaves(ex.root).reduce((s,r)=>s+r.power,0))} W.</p><p>Calcula amb els valors sense arrodonir; el resum mostra cinc xifres significatives.</p>`});
 out.push({title:'Resum de resultats',html:`<div class="cc-scroll"><table class="cc-table"><caption>Resultats del circuit</caption><tr><th>Element</th><th>R (Ω)</th><th>V (V)</th><th>I (A)</th><th>P (W)</th></tr>${[...leaves(ex.root),{...ex.root,id:'Total'}].map(r=>`<tr><th>${r.id}</th><td>${f(r.resistance)}</td><td>${f(r.voltage)}</td><td>${f(r.current)}</td><td>${f(r.power)}</td></tr>`).join('')}</table></div>`});return out;
}
const units={R:[['Ω',1],['kΩ',1000]],V:[['V',1],['mV',.001]],I:[['A',1],['mA',.001]],P:[['W',1],['mW',.001]]};
function answer(id,label,key,expected){fields.push({id,label,key,expected});return `<label class="cc-answer"><input id="${id}" inputmode="decimal" aria-label="${label}"><select id="${id}-unit" aria-label="Unitat: ${label}">${units[key].map(([u,v])=>`<option value="${v}">${u}</option>`).join('')}</select></label><span class="cc-status" id="${id}-status" role="status"></span>`;}
function practice(root,code){let error='';try{if(code){const {count,seed}=readCode(code);if(exercise?.code!==code){exercise=generate(count,seed);shown=0;}}else if(!exercise)exercise=generate(4,randomSeed());}catch(e){error=e.message;}if(error){root.innerHTML='<p role="alert" id="cc-error"></p><a href="#lab-005/practica">Generar un exercici</a>';root.querySelector('#cc-error').textContent=error;return;}
 const ex=exercise;fields=[];root.innerHTML=`<div class="cc-controls"><div><label for="cc-level">Nombre de resistències</label><select id="cc-level"><option value="2-3">Inicial · 2–3</option><option value="4-5">Bàsic · 4–5</option><option value="6-7">Intermedi · 6–7</option><option value="8-10">Avançat · 8–10</option></select></div><button id="cc-new">Nou exercici</button><form id="cc-load"><input id="cc-code-in" aria-label="Codi d’exercici" placeholder="TL-CC1-…" required><button>Obrir codi</button></form><span id="cc-code-error" role="status"></span></div><div class="cc-work"><section class="panel"><h2>Enunciat · ${ex.count} resistències</h2>${schematic(ex)}<p>Font ideal de ${ex.voltage} V. Connexions: ${expression(ex.root)} (+ sèrie, ∥ paral·lel).</p><p>Calcula R equivalent, corrent total i potència de la font; després, tensió, corrent i potència de cada resistència.</p><p class="cc-code">${ex.code}</p><div class="cc-actions"><button id="cc-copy">Copiar codi</button><button id="cc-link">Copiar enllaç</button></div><p id="cc-copy-status" role="status"></p></section><section class="panel"><h2>Les teves respostes</h2><p>Coma o punt decimal. Marge de correcció: 2 %. Pots comprovar respostes parcials.</p><form id="cc-answers"><table class="cc-table"><caption>Circuit total</caption>${[['R equivalent','R',ex.root.resistance],['Corrent total','I',ex.root.current],['Potència de la font','P',ex.root.power]].map(([label,key,v],i)=>`<tr><th>${label}</th><td>${answer('total-'+i,label,key,v)}</td></tr>`).join('')}</table><div class="cc-scroll"><table class="cc-table"><caption>Cada resistència</caption><tr><th>Element</th><th>Tensió</th><th>Corrent</th><th>Potència</th></tr>${leaves(ex.root).map(r=>`<tr><th>${r.id}</th>${[['V','voltage'],['I','current'],['P','power']].map(([k,prop])=>`<td>${answer(r.id+'-'+k,r.id+' '+({V:'tensió',I:'corrent',P:'potència'}[k]),k,r[prop])}</td>`).join('')}</tr>`).join('')}</table></div><div class="cc-actions"><button class="primary">Comprovar</button><button type="button" id="cc-clear">Esborrar respostes</button></div><p id="cc-feedback" role="status"></p></form></section></div><section class="panel cc-step"><h2>Resolució guiada</h2><div class="cc-actions"><button id="cc-next">Mostrar un pas</button><button id="cc-all">Mostrar tota la solució</button><button id="cc-hide">Amagar solució</button></div><p id="cc-progress" role="status"></p><div id="cc-steps"></div></section><p>No es desen ni s’envien respostes. En recarregar es perd el treball; el codi recupera l’enunciat.</p>`;
 const level=root.querySelector('#cc-level');level.value=ex.count<=3?'2-3':ex.count<=5?'4-5':ex.count<=7?'6-7':'8-10';
 root.querySelector('#cc-new').onclick=()=>{const [a,b]=level.value.split('-').map(Number),count=a+Math.floor(Math.random()*(b-a+1));exercise=generate(count,randomSeed());shown=0;location.hash=link('practica/'+exercise.code);};
 root.querySelector('#cc-load').onsubmit=e=>{e.preventDefault();try{const {count,seed}=readCode(root.querySelector('#cc-code-in').value);exercise=generate(count,seed);shown=0;location.hash=link('practica/'+exercise.code);practice(root,exercise.code);}catch(err){root.querySelector('#cc-code-error').textContent=err.message;}};
 const copy=async text=>{try{await navigator.clipboard.writeText(text);root.querySelector('#cc-copy-status').textContent='Copiat.';}catch{root.querySelector('#cc-copy-status').textContent='No s’ha pogut copiar. Selecciona el codi o copia l’adreça del navegador.';}};
 root.querySelector('#cc-copy').onclick=()=>copy(ex.code);root.querySelector('#cc-link').onclick=()=>{const url=new URL(location.href);url.hash=link('practica/'+ex.code);copy(url.href);};
 root.querySelector('#cc-answers').onsubmit=e=>{e.preventDefault();let tried=0,correct=0;for(const field of fields){const status=checkAnswer(root.querySelector('#'+field.id).value,+root.querySelector('#'+field.id+'-unit').value,field.expected),out=root.querySelector('#'+field.id+'-status');out.dataset.status=status;out.textContent={empty:'',invalid:'Escriu un nombre vàlid.',correct:'Correcte',incorrect:'Revisa el resultat.',units:'Revisa la unitat: factor 1000.'}[status];if(status!=='empty')tried++;if(status==='correct')correct++;}root.querySelector('#cc-feedback').textContent=tried?`${correct} de ${tried} respostes correctes.`:'Escriu almenys una resposta.';};
 root.querySelector('#cc-clear').onclick=()=>{root.querySelector('#cc-answers').reset();root.querySelectorAll('.cc-status').forEach(s=>s.textContent='');root.querySelector('#cc-feedback').textContent='';};
 const all=steps(ex),render=()=>{root.querySelector('#cc-steps').innerHTML=all.slice(0,shown).map((s,i)=>`<article class="cc-step"><h3>${i+1}. ${s.title}</h3>${s.html}</article>`).join('');root.querySelector('#cc-progress').textContent=`${shown} de ${all.length} passos`;root.querySelector('#cc-next').disabled=shown>=all.length;};root.querySelector('#cc-next').onclick=()=>{shown=Math.min(shown+1,all.length);render();};root.querySelector('#cc-all').onclick=()=>{shown=all.length;render();};root.querySelector('#cc-hide').onclick=()=>{shown=0;render();};render();
}
export function renderLab005(app,parts=[]){const mode=parts[0]||'';document.title='Circuits en corrent continu | TecLab';app.innerHTML=`<a class="back" href="#">← Catàleg TecLab</a>${mode?'<p><a href="#lab-005">← Portada del laboratori</a></p>':''}<p class="eyebrow">LAB-005 / CORRENT CONTINU · v1.0.0</p><h1>Anàlisi de circuits<br><span class="accent-text">en corrent continu.</span></h1><nav class="tabs" aria-label="Apartats del laboratori">${[['','Laboratori'],['fonaments','Fonaments'],['ajuda','Ajuda']].map(([p,t])=>`<a href="${link(p)}" ${mode===p?'aria-current="page"':''}>${t}</a>`).join('')}</nav><div id="cc-content"></div>`;const root=app.querySelector('#cc-content');
 if(mode==='practica')practice(root,parts[1]);else if(mode==='fonaments')root.innerHTML=`<article class="panel"><h2>Circuits resistius ideals</h2><p>Llei d’Ohm: V = R · I. En sèrie, R equivalent = R₁ + R₂ + …; en paral·lel, 1 / R equivalent = 1 / R₁ + 1 / R₂ + …</p><p>Redueix primer els grups interiors. Amb R equivalent calcula I total = V font / R equivalent; després desplega els grups per repartir tensions i corrents.</p><p>Kirchhoff: la suma dels corrents que entren a un nus és igual a la dels que en surten. La suma algebraica de tensions en una malla és zero.</p><p>Potència dissipada: P = V · I = I² · R = V² / R. La suma de potències dissipades és igual a la potència subministrada per la font.</p><p>1 kΩ = 1000 Ω; 1 mA = 0,001 A; 1 mW = 0,001 W. El marge del 2 % és de correcció de respostes, no una tolerància dels components.</p><p>Aquesta versió treballa amb circuits reductibles per sèrie i paral·lel. No inclou ponts, condensadors ni inductàncies.</p></article>`;else if(mode==='ajuda')root.innerHTML=`<article class="panel"><h2>Com practicar</h2><p>Tria entre 2–3, 4–5, 6–7 o 8–10 resistències i prem «Nou exercici». Resol el circuit a la llibreta i introdueix resultats amb la unitat corresponent.</p><p>«Comprovar» revisa els camps emplenats. Els missatges indiquen si cal revisar un resultat o les unitats. «Mostrar un pas» desplega la resolució progressivament amb esquemes equivalents.</p><p>Copia el codi TL-CC1 o l’enllaç per compartir exactament el mateix circuit. CC1 fixa la versió del generador. No és un codi d’accés i no identifica alumnes.</p><p>Els valors de resistència són nominals de sèries comercials; no s’estableix la potència nominal ni es proposa muntar físicament el circuit. La font i els components es consideren ideals.</p></article>`;else root.innerHTML=`<section class="panel"><h2>Pràctica resistiva</h2><p>Resol circuits en sèrie, paral·lel i mixtos amb una font contínua. Calcula resistència equivalent, tensions, corrents i potències, i comprova cada resultat.</p><div class="cc-intro-tools"><a href="#lab-005/practica">Començar la pràctica →</a><a href="#lab-005/fonaments">Consultar els fonaments</a></div><p>De 2 a 10 resistències · Exercicis compartibles · Sense comptes</p><p>Condensadors i inductàncies: ampliació prevista.</p></section>`;
}
