import { COLORS, color, roles, choices, decode, encode, parseNumber, number, ohms, defaults } from './resistor.js';
import { randomSeed } from '../../shared/services/exercises.js';
import { generateExercise, loadExercise, checkAnswer } from './exercises.js';

const state={count:4,bands:defaults(4),encodeCount:4,encoded:null,exercise:null,steps:0,checked:false,answer:null};
const roleName=(role,i)=>role==='digit'?`${i+1}a xifra`:role==='multiplier'?'Multiplicador':role==='tolerance'?'Tolerància':'Coeficient tèrmic';
const source='<p class="source">Referències: <a href="https://www.vishay.com/docs/49617/_color_code_card_draloric_resistors_vmn_ms6212_1501.pdf" target="_blank" rel="noopener">Vishay · Resistor Color Card</a> i <a href="https://www.te.com/en/products/passive-components/resistors/intersection/resistor-color-codes.html" target="_blank" rel="noopener">TE Connectivity · Resistor Color Codes</a>.</p>';
function options(role,selected,index=1){return choices(role,index).map(c=>`<option value="${c.id}" ${c.id===selected?'selected':''}>${c.name}${role==='digit'?` · ${c.digit}`:role==='multiplier'?` · ×10^${c.exponent}`:role==='tolerance'?` · ±${number(c.tolerance)} %`:` · ${c.tcr} ppm/K`}</option>`).join('');}
function countOptions(selected){return [4,5,6].map(n=>`<option ${n===selected?'selected':''}>${n}</option>`).join('');}
let figureSerial=0;
function figure(bands,{technical=false,hero=false}={}){
  const count=bands.length,rs=roles(count),uid=`resistor-${++figureSerial}`;
  const outline='M160 69 C160 56 168 48 181 48 H194 C205 48 213 57 225 58 H395 C407 57 415 48 426 48 H439 C452 48 460 56 460 69 V101 C460 114 452 122 439 122 H426 C415 122 407 113 395 112 H225 C213 113 205 122 194 122 H181 C168 122 160 114 160 101 Z';
  const positions=count===4?[213,251,289,374]:count===5?[204,238,272,306,383]:[202,234,266,298,360,397];
  const bodyColors=count===4?['#f5deb5','#cfad7b','#b49164']:['#dbebed','#8cb9c7','#648995'];
  return `<figure class="resistor-figure ${hero?'hero-figure':''}"><svg viewBox="0 0 620 190" role="img" aria-label="Resistència de ${count} bandes: ${bands.map(id=>color(id).name).join(', ')}">
    <defs><linearGradient id="${uid}-body" x1="0" y1="0" x2="0" y2="1"><stop stop-color="${bodyColors[2]}"/><stop offset=".2" stop-color="${bodyColors[0]}"/><stop offset=".5" stop-color="${bodyColors[1]}"/><stop offset=".82" stop-color="${bodyColors[2]}"/><stop offset="1" stop-color="${bodyColors[1]}"/></linearGradient><linearGradient id="${uid}-wire" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#656e78"/><stop offset=".35" stop-color="#e0e5e9"/><stop offset=".65" stop-color="#a2afb9"/><stop offset="1" stop-color="#5c6873"/></linearGradient><linearGradient id="${uid}-shine" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#0005"/><stop offset=".25" stop-color="#fff3"/><stop offset=".5" stop-color="#fff0"/><stop offset="1" stop-color="#0005"/></linearGradient><clipPath id="${uid}-clip"><path d="${outline}"/></clipPath></defs>
    <ellipse cx="310" cy="124" rx="158" ry="9" fill="#0003"/>
    <path d="M30 80H178V89H30zM442 80H590V89H442z" fill="url(#${uid}-wire)"/>
    <path d="${outline}" fill="url(#${uid}-body)" stroke="#766851" stroke-width="1"/>
    <g clip-path="url(#${uid}-clip)">${bands.map((id,i)=>`<path d="M${positions[i]} 44h${rs[i]==='tolerance'?20:16}v82h-${rs[i]==='tolerance'?20:16}z" fill="${color(id).hex}"/><path d="M${positions[i]} 44h${rs[i]==='tolerance'?20:16}v82h-${rs[i]==='tolerance'?20:16}z" fill="url(#${uid}-shine)"/>`).join('')}<path d="M180 57C195 53 209 66 225 66H395C410 65 423 55 439 57" fill="none" stroke="#fff5" stroke-width="2"/></g>
    <path d="M167 73v24M453 73v24" stroke="#0002" stroke-width="1.5"/>
    <path d="M180 147H440m-8-5 8 5-8 5" fill="none" stroke="#e4a34a" stroke-width="1.5"/><text x="310" y="174" fill="#b7c2ce" text-anchor="middle" font-family="system-ui" font-size="12">Lectura d’esquerra a dreta</text></svg>${hero?'':`<figcaption class="band-legend">${bands.map((id,i)=>`<span><i style="background:${color(id).hex}"></i><b>${i+1}</b> ${color(id).name}${technical?`<small>${roleName(rs[i],i)}</small>`:''}</span>`).join('')}</figcaption>`}</figure>`;
}

function result(bands){const r=decode(bands);return `<div class="schematic-stage">${figure(bands,{technical:true})}</div><div class="result-row"><div><span class="eyebrow">VALOR NOMINAL</span><div class="result">${ohms(r.nominal)}</div></div><div class="metrics"><div><small>Tolerància</small><strong>±${number(r.tolerance)} %</strong></div>${r.tcr!==null?`<div><small>Coeficient tèrmic</small><strong>${r.tcr} ppm/K</strong></div>`:''}</div></div><div class="interval"><small>Interval admissible</small><strong>${ohms(r.minimum)} – ${ohms(r.maximum)}</strong></div><p class="formula">${r.significant} × 10<sup>${r.exponent}</sup> = ${number(r.nominal)} Ω</p><details><summary>Veure el càlcul pas a pas</summary>${steps(bands,4)}</details>`;}
function steps(bands,n){const r=decode(bands);return `<ol class="steps">${n>=1?`<li>Les primeres ${r.digits.length} bandes donen ${r.digits.join(' · ')}. El nombre és <strong>${r.significant}</strong>.</li>`:''}${n>=2?`<li>${color(bands[r.digits.length]).name}: multiplica per 10<sup>${r.exponent}</sup>. Resultat: <strong>${ohms(r.nominal)}</strong>.</li>`:''}${n>=3?`<li>${color(bands[r.digits.length+1]).name}: ±${number(r.tolerance)} %. La variació és ${ohms(r.nominal*r.tolerance/100)}; l’interval és <strong>${ohms(r.minimum)} – ${ohms(r.maximum)}</strong>.</li>`:''}${n>=4&&r.tcr!==null?`<li>${color(bands.at(-1)).name}: coeficient tèrmic de <strong>${r.tcr} ppm/K</strong>. Indica el límit de variació relativa per grau; no determina el signe de la variació.</li>`:''}</ol>`;}
function navigate(path){const hash=`#lab-001${path?'/'+path:''}`;if(location.hash===hash) renderLab001(document.querySelector('#app'),path.split('/'));else location.hash=hash;}
function bindLinks(root){root.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>navigate(b.dataset.go));}
function base(root,mode){
  document.body.classList.add('lab-active');
  document.body.classList.toggle('lab-cover',mode==='');
  document.title='Codificació de resistències | TecLab';
  root.innerHTML=`<nav class="breadcrumbs" aria-label="Camí de navegació"><a href="#">Catàleg TecLab</a><span aria-hidden="true">/</span>${mode!==''?'<a href="#lab-001">LAB-001 · Resistències</a>':'<span>LAB-001 · Resistències</span>'}</nav>${mode!==''?'<a class="return-lab" href="#lab-001">← Tornar a la portada del laboratori</a>':''}<section class="lab-heading"><div class="eyebrow">LAB-001 / COMPONENTS ELECTRÒNICS</div><h1>${mode===''?'Codificació de<br><span>resistències.</span>':'Codificació de resistències'}</h1><p class="intro">${mode===''?'Aprèn a llegir una resistència, construeix el seu codi de colors i posa’t a prova amb exercicis compartibles.':'Lectura, codificació i pràctica · Resistències de 4, 5 i 6 bandes'}</p>${mode===''?`<div class="cover-meta"><span>EE10 · EE30 · EEB0</span><span>Accés lliure</span><span>v1.1.0</span></div>`:''}</section>${mode!==''?`<nav class="tabs" aria-label="Apartats del laboratori"><a href="#lab-001" class="${['lectura','crear','practica'].includes(mode)?'active':''}" ${['lectura','crear','practica'].includes(mode)?'aria-current="page"':''}>Laboratori</a><a href="#lab-001/fonaments" class="${mode==='fonaments'?'active':''}" ${mode==='fonaments'?'aria-current="page"':''}>Fonaments</a><a href="#lab-001/ajuda" class="${mode==='ajuda'?'active':''}" ${mode==='ajuda'?'aria-current="page"':''}>Ajuda</a><a class="lab-home" href="#lab-001">Portada del LAB</a></nav>`:''}<div id="lab-content"></div>`;
}
function modeBar(mode){return `<nav class="mode-bar" aria-label="Eines del laboratori">${[['lectura','Llegir bandes'],['crear','Crear una resistència'],['practica','Practicar']].map(([p,t])=>`<a href="#lab-001/${p}" ${mode===p?'aria-current="page"':''} class="${mode===p?'selected':''}">${t}</a>`).join('')}</nav>`;}
function cover(root){root.innerHTML=`<div class="cover-instrument"><div class="instrument-top"><span>R / IDENTIFICACIÓ</span><span>4 BANDES</span></div>${figure(['yellow','violet','red','gold'],{hero:true})}<div class="instrument-bottom"><span>4 · 7 · ×100</span><strong>4,7 kΩ <small>±5 %</small></strong></div></div><div class="cover-section-heading"><h2>Tria com vols treballar</h2><span>03 / EINES</span></div><div class="lab-tools">${[
  ['lectura','01','Llegir bandes','Modifica els colors i obtén el valor nominal, la tolerància i l’interval.','M20 40h30m180 0h30M50 20h180v40H50zM80 20v40m30-40v40m30-40v40m55-40v40'],
  ['crear','02','Crear una resistència','Introdueix un valor i troba la combinació de bandes que el representa.','M20 40h70m-10-8 10 8-10 8M120 20h140v40H120zM145 20v40m28-40v40m28-40v40m32-40v40'],
  ['practica','03','Practicar','Identifica resistències, comprova la resposta i consulta la resolució guiada.','M25 45l15 15 28-38M95 25h155M95 43h115M95 61h135']
].map(([path,n,title,text,d])=>`<a class="tool-card" href="#lab-001/${path}"><span class="tool-number">${n} / ${path==='practica'?'AUTOAVALUACIÓ':'EXPLORACIÓ'}</span>${path==='lectura'?figure(['yellow','violet','red','gold'],{hero:true}):path==='crear'?figure(['brown','black','black','red','brown'],{hero:true}):figure(['red','red','orange','silver'],{hero:true})}<h2>${title}</h2><p>${text}</p><span class="tool-arrow" aria-hidden="true">↗</span></a>`).join('')}<aside class="guide-card"><span class="tool-number">04 / CONSULTA</span><h2>Abans de començar</h2><p>Les xifres, el multiplicador i la tolerància: consulta la taula de colors i els exemples de lectura.</p><a href="#lab-001/fonaments">Obrir els fonaments →</a><a href="#lab-001/ajuda">Instruccions del laboratori →</a></aside></div><section class="cover-code"><div><h2>El mateix exercici per a tota la classe</h2><p>Obre un codi d’exercici o genera’n un a «Practicar». No cal cap compte.</p></div><form id="cover-code"><label for="cover-input">Codi d’exercici</label><div class="inline-fields"><input id="cover-input" placeholder="TL-R1-…" autocomplete="off" spellcheck="false" required><button class="primary">Obrir exercici</button></div><p role="status" id="cover-error"></p></form></section><div class="cover-bottom"><a href="#lab-001/fonaments">Consulta els fonaments →</a><a href="#lab-001/ajuda">Com funciona →</a><span>Sense desar dades d’alumnes</span></div>`;
  document.querySelector('#cover-code').onsubmit=e=>{e.preventDefault();try{const ex=loadExercise(document.querySelector('#cover-input').value);navigate('practica/'+ex.code);}catch(error){document.querySelector('#cover-error').textContent=error.message;}};
}
function reading(root){root.innerHTML=modeBar('lectura')+`<div class="workspace resistor-workspace reading-sheet"><section class="panel"><h2>Configura les bandes</h2><label for="read-count">Nombre de bandes</label><select id="read-count">${countOptions(state.count)}</select><div id="band-controls"></div><button id="read-reset">Reiniciar</button></section><section class="panel reading-result" id="read-result" aria-live="polite" aria-atomic="true"></section></div><p class="work-note">La banda de tolerància està separada de les xifres. En el model de 6 bandes, l’última indica el coeficient tèrmic.</p>`;
  const update=()=>document.querySelector('#read-result').innerHTML=result(state.bands);
  const controls=()=>{document.querySelector('#band-controls').innerHTML=roles(state.count).map((r,i)=>`<div class="band-field"><label for="read-band-${i}"><span class="band-number">${i+1}</span> ${roleName(r,i)}</label><select id="read-band-${i}">${options(r,state.bands[i],i)}</select></div>`).join('');roles(state.count).forEach((r,i)=>document.querySelector(`#read-band-${i}`).onchange=e=>{state.bands[i]=e.target.value;update();});update();};
  document.querySelector('#read-count').onchange=e=>{state.count=Number(e.target.value);state.bands=defaults(state.count);controls();};
  document.querySelector('#read-reset').onclick=()=>{state.bands=defaults(state.count);controls();};controls();
}
function creating(root){root.innerHTML=modeBar('crear')+`<div class="workspace resistor-workspace"><form class="panel" id="encode-form"><h2>Del valor als colors</h2><label for="encode-count">Nombre de bandes</label><select id="encode-count">${countOptions(state.encodeCount)}</select><label for="encode-value">Valor nominal</label><div class="inline-fields"><input id="encode-value" inputmode="decimal" value="4,7" required aria-describedby="encode-hint"><select id="encode-unit" aria-label="Unitat del valor nominal"><option value="1">Ω</option><option value="1000" selected>kΩ</option><option value="1000000">MΩ</option><option value="1000000000">GΩ</option></select></div><p class="field-hint" id="encode-hint">Coma o punt decimal. No utilitzis separadors de milers.</p><label for="encode-tolerance">Tolerància</label><select id="encode-tolerance">${options('tolerance','gold')}</select><div id="tcr-field"><label for="encode-tcr">Coeficient tèrmic</label><select id="encode-tcr">${options('tcr','brown')}</select></div><button class="primary" type="submit">Obtenir bandes</button><p class="error-message" role="status" id="encode-error"></p></form><section class="panel" id="encoded-result" aria-live="polite"><span class="eyebrow">REPRESENTACIÓ</span><h2>El teu codi de colors</h2><p>Introdueix el valor i prem «Obtenir bandes». Es mostrarà una codificació exacta, sense arrodonir el valor.</p><p>4 bandes: 2 xifres. 5 i 6 bandes: 3 xifres.</p></section></div>`;
  const tcr=()=>document.querySelector('#tcr-field').hidden=state.encodeCount!==6;tcr();
  document.querySelector('#encode-count').onchange=e=>{state.encodeCount=Number(e.target.value);tcr();document.querySelector('#encoded-result').innerHTML='<p>Prem «Obtenir bandes» per calcular amb el nou nombre de bandes.</p>';document.querySelector('#encode-error').textContent='';};
  document.querySelector('#encode-form').onsubmit=e=>{e.preventDefault();const output=document.querySelector('#encoded-result');try{const nominal=parseNumber(document.querySelector('#encode-value').value)*Number(document.querySelector('#encode-unit').value);const bands=encode(nominal,state.encodeCount,document.querySelector('#encode-tolerance').value,document.querySelector('#encode-tcr').value);document.querySelector('#encode-error').textContent='';output.innerHTML=result(bands);}catch(error){document.querySelector('#encode-error').textContent=error.message;output.innerHTML='<p>No s’ha generat cap codi. Revisa el valor indicat.</p>';}};
}
function practice(root,code){
  let invalid=null;
  try {if(code){const ex=loadExercise(code);if(state.exercise?.code!==ex.code){state.exercise=ex;state.steps=0;state.checked=false;}}else if(!state.exercise){state.exercise=generateExercise(4,randomSeed());state.steps=0;state.checked=false;}}catch(error){invalid=error.message;}
  if(invalid){root.innerHTML=modeBar('practica')+`<div class="panel"><h2>No s’ha pogut obrir l’exercici</h2><p id="invalid-code" role="alert"></p><button class="primary" data-go="practica">Generar un exercici nou</button></div>`;document.querySelector('#invalid-code').textContent=invalid;bindLinks(root);return;}
  const ex=state.exercise,totalSteps=ex.count===6?4:3;
  root.innerHTML=modeBar('practica')+`<section class="exercise-toolbar"><div><label for="practice-count">Tipus d’exercici</label><select id="practice-count">${countOptions(ex.count)}</select><button id="new-exercise">Nou exercici</button></div><form id="load-code"><label for="exercise-input">Obrir un codi d’exercici</label><div class="inline-fields"><input id="exercise-input" placeholder="TL-R1-…" required autocomplete="off" spellcheck="false"><button>Obrir</button></div><p role="status" id="load-error"></p></form></section><div class="practice-layout"><section class="panel exercise-visual"><span class="eyebrow">01 / ENUNCIAT</span><h2>Identifica aquesta resistència</h2>${figure(ex.bands)}<p>Llegeix les bandes d’esquerra a dreta. Escriu el valor nominal i la tolerància${ex.count===6?', i identifica el coeficient tèrmic':''}.</p><div class="exercise-code"><label for="current-code">Codi reproduïble · Generador R1</label><input id="current-code" readonly value="${ex.code}"><button id="copy-code">Copiar codi</button><button id="copy-link">Copiar enllaç</button><p role="status" id="copy-status"></p></div></section><form class="panel" id="check-answer"><span class="eyebrow">02 / RESPOSTES</span><h2>La teva resposta</h2><label for="answer-value">Valor nominal</label><div class="inline-fields"><input id="answer-value" inputmode="decimal" required aria-describedby="answer-hint"><select id="answer-unit" aria-label="Unitat de la resposta"><option value="1">Ω</option><option value="1000">kΩ</option><option value="1000000">MΩ</option><option value="1000000000">GΩ</option></select></div><p class="field-hint" id="answer-hint">Coma o punt decimal, sense separadors de milers.</p><label for="answer-tolerance">Tolerància (%)</label><select id="answer-tolerance" required><option value="">Tria una tolerància</option>${choices('tolerance').map(c=>`<option value="${c.tolerance}">±${number(c.tolerance)} %</option>`).join('')}</select>${ex.count===6?`<label for="answer-tcr">Coeficient tèrmic (ppm/K)</label><select id="answer-tcr" required><option value="">Tria un coeficient</option>${choices('tcr').map(c=>`<option value="${c.tcr}">${c.tcr} ppm/K</option>`).join('')}</select>`:''}<button class="primary">Comprovar resposta</button><div id="feedback" class="feedback" role="status"></div><p class="field-hint">Es comprova el valor nominal; un valor dins de l’interval de tolerància no substitueix la resposta exacta.</p></form></div><section class="panel solution-panel"><div class="solution-heading"><h2>03 / Resolució guiada</h2><div><button id="show-step">Mostrar un pas</button><button id="show-all">Veure la solució</button></div></div><div id="solution" aria-live="polite"></div><p class="work-note">Les respostes es comproven al navegador. No es guarden ni s’envien.</p></section>`;
  const newExercise=()=>{state.exercise=generateExercise(Number(document.querySelector('#practice-count').value),randomSeed());state.steps=0;state.checked=false;navigate('practica/'+state.exercise.code);};
  document.querySelector('#new-exercise').onclick=newExercise;
  document.querySelector('#practice-count').onchange=newExercise;
  document.querySelector('#load-code').onsubmit=e=>{e.preventDefault();try{const next=loadExercise(document.querySelector('#exercise-input').value);state.steps=0;state.checked=false;state.exercise=next;navigate('practica/'+next.code);}catch(error){document.querySelector('#load-error').textContent=error.message;}};
  async function copy(text){const status=document.querySelector('#copy-status');try{await navigator.clipboard.writeText(text);status.textContent='Copiat.';}catch{status.textContent='No s’ha pogut copiar automàticament. Selecciona i copia el codi del camp.';}}
  document.querySelector('#copy-code').onclick=()=>copy(ex.code);
  document.querySelector('#copy-link').onclick=()=>{const url=new URL(location.href);url.hash='lab-001/practica/'+ex.code;copy(url.href);};
  document.querySelector('#check-answer').onsubmit=e=>{e.preventDefault();const feedback=document.querySelector('#feedback');try{const value=parseNumber(document.querySelector('#answer-value').value)*Number(document.querySelector('#answer-unit').value);const {nominalOK,toleranceOK,tcrOK,correct}=checkAnswer(ex.bands,value,Number(document.querySelector('#answer-tolerance').value),ex.count===6?Number(document.querySelector('#answer-tcr').value):null);feedback.className='feedback '+(correct?'correct':'incorrect');feedback.textContent=correct?'Resposta correcta. Has identificat totes les magnituds.':`Revisa ${[!nominalOK?'el valor nominal':null,!toleranceOK?'la tolerància':null,!tcrOK?'el coeficient tèrmic':null].filter(Boolean).join(' i ')}. Pots tornar-ho a provar o mostrar un pas.`;state.checked=true;}catch(error){feedback.className='feedback incorrect';feedback.textContent=error.message;}};
  const show=()=>{document.querySelector('#solution').innerHTML=state.steps?steps(ex.bands,state.steps):'<p>Prova de resoldre l’exercici abans de consultar els passos.</p>';document.querySelector('#show-step').disabled=state.steps>=totalSteps;};
  document.querySelector('#show-step').onclick=()=>{state.steps=Math.min(totalSteps,state.steps+1);show();};document.querySelector('#show-all').onclick=()=>{state.steps=totalSteps;show();};show();
}
function fundamentals(root){root.innerHTML=`<div class="theory-layout"><article class="panel"><h2>Com es llegeixen les bandes?</h2><p>Comença per l’extrem on la primera banda queda més a prop de la vora. La banda de tolerància acostuma a estar separada de les xifres. Aquest laboratori utilitza la codificació axial convencional: 2 xifres en 4 bandes, 3 en 5 i 6 bandes.</p><div class="table-scroll"><table><caption>Funció de les bandes</caption><thead><tr><th>Model</th><th>Xifres</th><th>Multiplicador</th><th>Tolerància</th><th>TCR</th></tr></thead><tbody><tr><td>4 bandes</td><td>1 i 2</td><td>3</td><td>4</td><td>—</td></tr><tr><td>5 bandes</td><td>1, 2 i 3</td><td>4</td><td>5</td><td>—</td></tr><tr><td>6 bandes</td><td>1, 2 i 3</td><td>4</td><td>5</td><td>6</td></tr></tbody></table></div><h3>Del codi al valor</h3><p class="formula">R = xifres significatives × 10<sup>n</sup> Ω</p><p>Groc, violeta, vermell i daurat: 47 × 100 = 4 700 Ω = 4,7 kΩ, amb ±5 %.</p><h3>La tolerància</h3><p>Indica quant pot diferir el valor real del nominal. Per a 4,7 kΩ amb ±5 %, la variació és 235 Ω: de 4 465 a 4 935 Ω.</p><p class="formula">R mín. = R × (1 − t/100)<br>R màx. = R × (1 + t/100)</p><h3>La sisena banda</h3><p>El coeficient tèrmic (TCR) expressa una variació relativa per grau en ppm/K. Una diferència d’1 K equival a una diferència d’1 °C. Per exemple, 100 ppm/K equival a 0,01 % per grau. La banda no determina per si sola el signe de la variació.</p><h3>Valors representables</h3><p>«Crear una resistència» utilitza multiplicadors de 10⁻² a 10⁹ i exigeix una representació exacta. Les 4 bandes permeten 2 xifres significatives; les 5 i 6, 3. Això no garanteix que el valor sigui comercial ni que pertanyi a una sèrie E.</p><p class="work-note">No s’inclouen resistències de 0 Ω, codis SMD ni variants militars o de fiabilitat. Davant d’un component real amb marcatges especials, consulta la fitxa del fabricant.</p>${source}</article><aside class="panel color-reference"><h2>Taula de colors</h2><div class="table-scroll"><table><caption>Valors utilitzats al laboratori</caption><thead><tr><th>Color</th><th>Xifra</th><th>×10ⁿ</th><th>± %</th><th>ppm/K</th></tr></thead><tbody>${COLORS.map(c=>`<tr><th scope="row"><span class="swatch" style="background:${c.hex}"></span>${c.name}</th><td>${c.digit??'—'}</td><td>${c.exponent}</td><td>${c.tolerance===null?'—':number(c.tolerance)}</td><td>${c.tcr??'—'}</td></tr>`).join('')}</tbody></table></div><p class="field-hint">El color va acompanyat del nom. La primera xifra no pot ser zero.</p></aside></div>`;}
function help(root){root.innerHTML=`<article class="panel help-content"><h2>Treballar amb el LAB-001</h2><h3>Llegir bandes</h3><p>Tria 4, 5 o 6 bandes. Cada selector mostra els colors vàlids per a la seva funció. El dibuix i els resultats s’actualitzen en modificar un color. «Reiniciar» recupera l’exemple inicial del model.</p><h3>Crear una resistència</h3><p>Indica el valor, la unitat i la tolerància; en 6 bandes també el TCR. Escriu decimals amb coma o punt i sense separadors de milers. Si el valor no es pot representar exactament, apareixerà un missatge: el laboratori no l’arrodoneix.</p><h3>Practicar</h3><p>Tria el nombre de bandes i resol l’exercici. Pots canviar d’unitat: 4 700 Ω i 4,7 kΩ són equivalents. Prem «Comprovar resposta» per revisar el valor nominal, la tolerància i, en 6 bandes, el coeficient tèrmic. Pots repetir l’intent sense límit.</p><h3>Compartir un exercici</h3><p>«Copiar codi» comparteix el codi TL-R1. «Copiar enllaç» inclou aquest codi a l’adreça del laboratori. Obrir-lo genera les mateixes bandes, sense dades d’alumnes. R1 identifica la versió del generador i es conservarà per als codis existents.</p><p>El codi d’exercici no és un codi d’accés. TECLAB-001 només localitza aquest laboratori des de la portada del portal.</p><h3>Consultar la solució</h3><p>«Mostrar un pas» revela primer les xifres, després el multiplicador i el resultat, i finalment la tolerància i el TCR. «Veure la solució» mostra tots els passos.</p><h3>Dades i accessibilitat</h3><p>No s’utilitzen comptes, galetes ni emmagatzematge de respostes. En recarregar la pàgina es perd el treball; un codi d’exercici permet recuperar l’enunciat. Els selectors i botons es poden utilitzar amb teclat i tots els colors tenen una etiqueta de text.</p></article>`;}
export function renderLab001(root,parts=[]){
  let mode=parts[0]??'';
  if(!['','lectura','crear','practica','fonaments','ajuda'].includes(mode)) mode='';
  base(root,mode);const content=root.querySelector('#lab-content');
  if(mode==='')cover(content);else if(mode==='lectura')reading(content);else if(mode==='crear')creating(content);else if(mode==='practica')practice(content,parts[1]);else if(mode==='fonaments')fundamentals(content);else help(content);
}

export { figure as resistorFigure };
